' UML Boilerplate'
@startuml db_structure
'Users structure'
class User {
    +String username
    -String password
    +String spotifyId
    +String bio
    +String location
    +String link
    +Favorites favorites
    +List<Playlist> annotatedPlaylists
}

'Favorites structure'
class Favorites {
    +List<Playlist> genre
    +List<Playlist> artist
    +List<Playlist> album
}

'Playlist structure'
class Playlist {
    +String spotifyId
    +List<String> tags
}

'Song structure'
class Song {
    +String spotifyId
}

'Notification Structure'
class Notification {
    +String title
    +String message
    +String type
    +List<User> receiver
    +String status
    +int createdAt
    +int expiresAt
}

Playlist "1" *-- "*" Song

User "1" *-- "*" Playlist

User "1" *-- "1" Favorites
@enduml